#!/usr/bin/env node
/**
 * Emits SQL that fills the reports table with the sample observations from the
 * design mock, timestamped relative to *now* so the aggregation window and the
 * 「N分前」 labels look alive.
 *
 * Development only — never run this against the production database.
 *
 *   node scripts/seed.mjs > .seed.sql
 *   wrangler d1 execute drink-status --local --file .seed.sql
 */

const MINUTE = 60_000;
const now = Date.now();

/**
 * [subject, action, user letter, minutes ago, level?]
 *
 * `level` is what a sighting saw (shared/domain.ts SIGHTING_LEVELS). Rows
 * without one stand in for drink-expanded votes and for anything posted before
 * the bands existed, so the sample board exercises both halves of the average.
 */
const SEED = [
  ['coffeeBeans', 'available', 'A', 2, 95],
  ['coffeeBeans', 'available', 'E', 4, 60],
  ['coffeeBeans', 'available', 'F', 6],
  ['coffeeBeans', 'available', 'G', 9, 95],
  ['coffeeBeans', 'low', 'H', 8, 30],
  ['cocoaPowder', 'low', 'B', 7, 30],
  ['cocoaPowder', 'low', 'I', 4, 10],
  ['cocoaPowder', 'low', 'J', 9, 30],
  ['cocoaPowder', 'available', 'K', 5, 60],
  ['milkPowder', 'refilled', 'C', 18],
  ['milkPowder', 'available', 'L', 16, 95],
  ['machine', 'available', 'D', 24],
  // Ice runs down faster than the powders, so the sample data shows it low.
  ['ice', 'low', 'A', 3, 10],
  ['ice', 'low', 'E', 6, 30],
  ['ice', 'available', 'M', 11, 60],
  // Queue reports sit inside the 10-minute queue window; the older one is
  // there to show the recency weighting doing its job.
  ['queue', 'medium', 'B', 1],
  ['queue', 'medium', 'F', 2],
  ['queue', 'short', 'G', 7],
];

const users = [...new Set(SEED.map(([, , letter]) => letter))].sort();

const lines = [
  '-- Generated by scripts/seed.mjs — development sample data.',
  'DELETE FROM reports;',
  "DELETE FROM users WHERE id LIKE 'seed-%';",
];

for (const letter of users) {
  lines.push(
    `INSERT OR REPLACE INTO users (id, label, created_at) VALUES ('seed-${letter}', '利用者${letter}', ${now});`,
  );
}

for (const [subject, action, letter, minutesAgo, level] of SEED) {
  const createdAt = now - minutesAgo * MINUTE;
  lines.push(
    `INSERT INTO reports (id, subject, action, user_id, user_label, created_at, level) VALUES ` +
      `('seed-${subject}-${letter}', '${subject}', '${action}', 'seed-${letter}', '利用者${letter}', ${createdAt}, ${level ?? 'NULL'});`,
  );
}

process.stdout.write(lines.join('\n') + '\n');
