#!/usr/bin/env node
/**
 * Emits SQL that fills the reports table with the sample observations from the
 * design mock, timestamped relative to *now* so the aggregation window and the
 * 「N分前」 labels look alive.
 *
 * Development only — never run this against the production database.
 *
 *   node scripts/seed.mjs > .seed.sql
 *   wrangler d1 execute drink-status --local --file .seed.sql
 */

const MINUTE = 60_000;
const now = Date.now();

/** [subject, action, user letter, minutes ago] */
const SEED = [
  ['coffeeBeans', 'available', 'A', 2],
  ['coffeeBeans', 'available', 'E', 4],
  ['coffeeBeans', 'available', 'F', 6],
  ['coffeeBeans', 'available', 'G', 9],
  ['coffeeBeans', 'low', 'H', 8],
  ['cocoaPowder', 'low', 'B', 7],
  ['cocoaPowder', 'low', 'I', 4],
  ['cocoaPowder', 'low', 'J', 9],
  ['cocoaPowder', 'available', 'K', 5],
  ['milkPowder', 'refilled', 'C', 18],
  ['milkPowder', 'available', 'L', 16],
  ['machine', 'available', 'D', 24],
];

const users = [...new Set(SEED.map(([, , letter]) => letter))].sort();

const lines = [
  '-- Generated by scripts/seed.mjs — development sample data.',
  'DELETE FROM reports;',
  "DELETE FROM users WHERE id LIKE 'seed-%';",
];

for (const letter of users) {
  lines.push(
    `INSERT OR REPLACE INTO users (id, label, created_at) VALUES ('seed-${letter}', '利用者${letter}', ${now});`,
  );
}

for (const [subject, action, letter, minutesAgo] of SEED) {
  const createdAt = now - minutesAgo * MINUTE;
  lines.push(
    `INSERT INTO reports (id, subject, action, user_id, user_label, created_at) VALUES ` +
      `('seed-${subject}-${letter}', '${subject}', '${action}', 'seed-${letter}', '利用者${letter}', ${createdAt});`,
  );
}

process.stdout.write(lines.join('\n') + '\n');
